# Site settings
course_name: Introduction to Computational Neuroscience 
course_description: "This module will introduce students to computational and theoretical approaches in neuroscience. Emphasis will be on specific questions and how those questions can be answered with computational methods."

course_semester: "Spring 2023"

baseurl: "/nepr208" # the subpath of your site, e.g. /blog/
url: "http://druckmann-lab.github.io/" # the base hostname & protocol for your site

schoolname: "Stanford University"
schoolurl: "https://stanford.edu"
#twitter_username: username 

address: |
    Stanford University
    Stanford, CA
    USA

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%a %-m/%-d/%Y"
onlydateformat: "%-m/%-d/%Y"
timeformat: "%-I:%M %p"

timezone: America/Los_Angeles

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
